// Generated by https://pagedraw.io/pages/10133
import React from 'react';
import './bot_o_menu.css';


function render() {
    return <div className="pd-onactive-parent pd-onhover-parent bot_o_menu">
        <div className="pd-onactive bot_o_menu-_active-2">
            <div className="bot_o_menu-0-0">
                <div className="bot_o_menu-text-2">Partidas</div>
            </div>
        </div>
        { (('default') === "default") ?
            <div className="bot_o_menu-default-2">
                <div className="bot_o_menu-1-0-0">
                    <div className="bot_o_menu-text-6">
                        { this.props.text }
                    </div>
                </div>
            </div>
        : null}
        <div className="pd-onhover bot_o_menu-_hover-5">
            <div className="bot_o_menu-2-0">
                <div className="bot_o_menu-text-0">Partidas</div>
            </div>
            <div className="bot_o_menu-2-1">
                <div className="bot_o_menu-rectangle-0" /> 
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
