// Generated by https://pagedraw.io/pages/10133
import React from 'react';
import './botao_menu.css';


function render() {
    return <div className="pd-onactive-parent pd-onhover-parent botao_menu">
        <div className="pd-onactive botao_menu-_active-2">
            <div className="botao_menu-0-0" /> 
            <div className="botao_menu-0-1">
                <div className="botao_menu-text-2">
                    { this.props.item }
                </div>
            </div>
        </div>
        { (('default') === "default") ?
            <div className="botao_menu-default-2">
                <div className="botao_menu-1-0-0" /> 
                <div className="botao_menu-1-0-1">
                    <div className="botao_menu-text-6">
                        { this.props.item }
                    </div>
                </div>
            </div>
        : null}
        <div className="pd-onhover botao_menu-_hover-5">
            <div className="botao_menu-2-0" /> 
            <div className="botao_menu-2-1">
                <div className="botao_menu-text-0">
                    { this.props.item }
                </div>
            </div>
            <div className="botao_menu-2-2">
                <div className="botao_menu-rectangle-0" /> 
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
