// Generated by https://pagedraw.io/pages/10133
import React from 'react';
import './card_selecao.css';


function render() {
    return <div className="card_selecao-card_selecao-8">
        <div className="card_selecao-0">
            <div className="card_selecao-rectangle_2">
                <div className="card_selecao-0-0-0">
                    <div className="card_selecao-rectangle_4">
                        <div className="card_selecao-0-0-0-0-0">
                            <div className="card_selecao-tipocard-5">
                                { this.props.cardSelecao.tipoCard }
                            </div>
                        </div>
                    </div>
                </div>
                <div className="card_selecao-0-0-1">
                    <img src={this.props.cardSelecao.bandeira} className="card_selecao-bandeira-9" /> 
                    <div className="card_selecao-0-0-1-1">
                        <div className="card_selecao-0-0-1-1-0">
                            <div className="card_selecao-nomepais-0">
                                { this.props.cardSelecao.nomePais }
                            </div>
                        </div>
                        <div className="card_selecao-0-0-1-1-1">
                            <div className="card_selecao-numero-0">
                                { this.props.cardSelecao.numero }
                            </div>
                            <div className="card_selecao-tiponumero-8">
                                { this.props.cardSelecao.tipoNumero }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
