// Generated by https://pagedraw.io/pages/10133
import React from 'react';
import './card_jogador.css';


function render() {
    return <div className="card_jogador-card_jogador-9">
        <div className="card_jogador-0">
            <div className="card_jogador-rectangle_9">
                <div className="card_jogador-0-0-0">
                    <div className="card_jogador-rectangle_4">
                        <div className="card_jogador-0-0-0-0-0">
                            <div className="card_jogador-tipocard-5">
                                { this.props.card.tipoCard }
                            </div>
                        </div>
                    </div>
                </div>
                <div className="card_jogador-0-0-1">
                    <div className="card_jogador-0-0-1-0">
                        <div className="card_jogador-0-0-1-0-0">
                            <div className="card_jogador-nomejogador-2">
                                { this.props.card.nomeJogador }
                            </div>
                        </div>
                    </div>
                    <div className="card_jogador-0-0-1-1">
                        <div className="card_jogador-0-0-1-1-0">
                            <div className="card_jogador-numero-9">
                                { this.props.card.numero }
                            </div>
                        </div>
                    </div>
                    <div className="card_jogador-icone-9" style={{"backgroundImage": ("url('"+(this.props.card.icone)+"')")}} /> 
                </div>
                <div className="card_jogador-0-0-2" /> 
                <div className="card_jogador-0-0-3">
                    <div className="card_jogador-rectangle_4-1">
                        <div className="card_jogador-0-0-3-0-0">
                            <img src={this.props.card.bandeira} className="card_jogador-bandeira-0" /> 
                            <div className="card_jogador-0-0-3-0-0-1">
                                <div className="card_jogador-0-0-3-0-0-1-0">
                                    <div className="card_jogador-nomepais-3">
                                        { this.props.card.nomePais }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
