// Generated by https://pagedraw.io/pages/10133
import React from 'react';
import Selecao from './selecao';
import './grupo.css';


function render() {
    return <div className="grupo-grupo-2">
        <div className="grupo-0">
            <div className="grupo-rectangle_1">
                <div className="grupo-0-0-0">
                    <div className="grupo-grupo-5">Grupo</div>
                    <div className="grupo-numerogrupo-0">
                        { this.props.numeroGrupo }
                    </div>
                </div>
            </div>
        </div>
        <div className="grupo-1">
            <div className="grupo-selecao_instance-6">
                <Selecao nomeSelecao={""} pontos={"P"} jogos={"J"} vitorias={"V"} empates={"E"} derrotas={"D"} golsPro={"GP"} golsContra={"GC"} saldo={"SG"} porcentagem={"%"} font={14} img_src={""} /> 
            </div>
        </div>
        <div className="grupo-2">
            <div className="grupo-2-0">
                { this.props.selecoes.map((elem, i) => {
                    return <div key={i} className="grupo-rectangle_3">
                        <div className="grupo-2-0-0-0-0">
                            <div className="grupo-primeiraselecao-2">
                                <Selecao nomeSelecao={elem.nome} pontos={elem.pontos} jogos={elem.jogos} vitorias={elem.vitorias} empates={elem.empates} derrotas={elem.derrotas} golsPro={elem.golsPro} golsContra={elem.golsContra} saldo={elem.saldo} porcentagem={elem.porcentagem} font={22} img_src={elem.bandeira} /> 
                            </div>
                        </div>
                    </div>;
                }) }
            </div>
        </div>
        <div className="grupo-3" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
