// Generated by https://pagedraw.io/pages/10133
import React from 'react';
import './jogador.css';


function render() {
    return <div className="jogador-jogador-5">
        <div className="jogador-0">
            <div className="jogador-rectangle_1">
                <div className="jogador-0-0-0">
                    <div className="jogador-numero-3">
                        { this.props.camisa }
                    </div>
                    <div className="jogador-nome-3">{ this.props.nome }</div>
                </div>
            </div>
            <div className="jogador-0-1" /> 
            <div className="jogador-0-2">
                <div className="jogador-0-2-0">
                    <div className="jogador-cartoesvermelhos-2">
                        { this.props.cartoesVermelhos }
                    </div>
                </div>
            </div>
            <div className="jogador-image_2" /> 
            <div className="jogador-0-4">
                <div className="jogador-0-4-0">
                    <div className="jogador-cartoes_amarelos-8">
                        { this.props.cartoesAmarelos }
                    </div>
                </div>
            </div>
            <div className="jogador-image-0" /> 
            <div className="jogador-0-6">
                <div className="jogador-0-6-0">
                    <div className="jogador-gols-7">{ this.props.gols }</div>
                </div>
            </div>
            <div className="jogador-image_3" /> 
            <div className="jogador-0-8">
                <div className="jogador-0-8-0">
                    <div className="jogador-posicao-1">
                        { this.props.posicao }
                    </div>
                </div>
            </div>
        </div>
        <div className="jogador-1" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
