// Generated by https://pagedraw.io/pages/10133
import React from 'react';
import './jogador.css';


function render() {
    return <div className="jogador-jogador-5">
        <div className="jogador-0" /> 
        <div className="jogador-1">
            <div className="jogador-rectangle_1">
                <div className="jogador-1-0-0">
                    <div className="jogador-1-0-0-0" /> 
                    <div className="jogador-nome-3">Neymar Junior</div>
                    <div className="jogador-1-0-0-2" /> 
                    <div className="jogador-1-0-0-3">
                        <div className="jogador-1-0-0-3-0">
                            <div className="jogador-numero-3">10</div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="jogador-1-1">
                <div className="jogador-1-1-0">
                    <div className="jogador-cartoesvermelhos-2">7</div>
                </div>
            </div>
            <div className="jogador-1-2" /> 
            <div className="jogador-image_2" /> 
            <div className="jogador-1-4" /> 
            <div className="jogador-1-5">
                <div className="jogador-1-5-0">
                    <div className="jogador-cartoes_amarelos-8">7</div>
                </div>
            </div>
            <div className="jogador-1-6" /> 
            <div className="jogador-image-0" /> 
            <div className="jogador-1-8" /> 
            <div className="jogador-1-9">
                <div className="jogador-1-9-0">
                    <div className="jogador-gols-7">7</div>
                </div>
            </div>
            <div className="jogador-1-10" /> 
            <div className="jogador-image_3" /> 
            <div className="jogador-1-12" /> 
            <div className="jogador-1-13">
                <div className="jogador-1-13-0">
                    <div className="jogador-posicao-1">Atacante</div>
                </div>
            </div>
            <div className="jogador-1-14" /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
