// Generated by https://pagedraw.io/pages/10133
import React from 'react';
import './lance.css';


function render() {
    return <div className="lance-lance-1">
        <div className="lance-0">
            <div className="lance-0-0">
                <div className="lance-0-0-0">
                    <div className="lance-tempo-4">{ this.props.tempo }</div>
                </div>
            </div>
            <div className="lance-rectangle_1">
                <div className="lance-0-1-0">
                    <div className="lance-titulolance-9">
                        { this.props.tituloLance }
                    </div>
                </div>
                <div className="lance-0-1-1">
                    <div className="lance-desclance-0">
                        { this.props.descLance }
                    </div>
                </div>
            </div>
        </div>
        <div className="lance-1">
            <div className="lance-line_3" /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
