// Generated by https://pagedraw.io/pages/10133
import React from 'react';
import Botao_menu from './botao_menu';
import './menu.css';


function render() {
    return <div className="menu-menu-2">
        <div className="menu-0">
            <div className="menu-0-0">
                <div className="menu-0-0-0">
                    <div className="menu-logo-0" style={{"backgroundImage": ("url('"+(this.props.img_src)+"')")}} /> 
                </div>
            </div>
            <a href="/grupos" className="menu-0-1">
                <div className="menu-bot_o_menu_instance-8">
                    <Botao_menu item={"Grupos"} /> 
                </div>
            </a>
            <a href="/partidas" className="menu-0-2">
                <div className="menu-bot_o_menu_instance_2">
                    <Botao_menu item={"Partidas"} /> 
                </div>
            </a>
            <div className="menu-bot_o_menu_instance_2-1">
                <Botao_menu item={"Estatísticas"} /> 
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
