// Generated by https://pagedraw.io/pages/10133
import React from 'react';
import Bot_o_menu from './bot_o_menu';
import './menu.css';


function render() {
    return <div className="menu-menu-2">
        <div className="menu-0">
            <div className="menu-0-0">
                <div className="menu-0-0-0">
                    <div className="menu-logo-0" /> 
                </div>
            </div>
            <div className="menu-bot_o_menu_instance-8">
                <Bot_o_menu text={"Seleções"} /> 
            </div>
            <div className="menu-bot_o_menu_instance_2">
                <Bot_o_menu text={"Partidas"} /> 
            </div>
            <div className="menu-bot_o_menu_instance_2-1">
                <Bot_o_menu text={"Estatísticas"} /> 
            </div>
            <div className="menu-bot_o_menu_instance_2-0">
                <Bot_o_menu text={"Estádios"} /> 
            </div>
            <div className="menu-0-5" /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
