// Generated by https://pagedraw.io/pages/10133
import React from 'react';
import './sele_o.css';

function render() {
    return <div className="sele_o-sele_o-7">
        <div className="sele_o-0">
            <div className="sele_o-0-0">
                <div className="sele_o-0-0-0">
                    <div className="sele_o-nomeselecao-4">{"Seleção X"}</div>
                </div>
            </div>
            <div className="sele_o-qtdpontos-4">X</div>
            <div className="sele_o-qtdjogos-0">X</div>
            <div className="sele_o-qtdvitorias-5">X</div>
            <div className="sele_o-qtdempates-6">X</div>
            <div className="sele_o-qtdderrotas-2">X</div>
            <div className="sele_o-golspro-4">X</div>
            <div className="sele_o-golscontra-2">X</div>
            <div className="sele_o-saldogols-7">X</div>
            <div className="sele_o-rendimento-8">X</div>
        </div>
        <div className="sele_o-1">
            <div className="sele_o-line_2" /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}