// Generated by https://pagedraw.io/pages/10133
import React from 'react';
import './selecoes.css';


function render() {
    return <div className="selecoes-selecoes-7">
        <div className="selecoes-0">
            <div className="selecoes-0-0">
                <div className="selecoes-0-0-0">
                    <div className="selecoes-nomeselecao1">BRASIL</div>
                </div>
            </div>
            <div className="selecoes-0-1">
                <div className="selecoes-0-1-0">
                    <div className="selecoes-bandeiraselecao1" /> 
                </div>
            </div>
            <div className="selecoes-0-2">
                <div className="selecoes-0-2-0">
                    <div className="selecoes-golsselecao1">5</div>
                </div>
            </div>
            <div className="selecoes-0-3">
                <div className="selecoes-0-3-0">
                    <div className="selecoes-text_3">x</div>
                </div>
            </div>
            <div className="selecoes-0-4">
                <div className="selecoes-0-4-0">
                    <div className="selecoes-golsselecao2">4</div>
                </div>
            </div>
            <div className="selecoes-0-5">
                <div className="selecoes-0-5-0">
                    <div className="selecoes-bandeiraselecao1-3" /> 
                </div>
            </div>
            <div className="selecoes-0-6">
                <div className="selecoes-0-6-0">
                    <div className="selecoes-nomeselecao1-3">ARGENTINA</div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
