// Generated by https://pagedraw.io/pages/10133
import React from 'react';
import './selecao.css';

function render() {
    return <div className="selecao-selecao-7">
        <div className="selecao-0">
            <div className="selecao-0-0">
                <div className="selecao-0-0-0">
                    <div className="selecao-nomeselecao-4">
                        { this.props.nomeSelecao }
                    </div>
                </div>
            </div>
            <div className="selecao-qtdpontos-4">
                { this.props.pontos }
            </div>
            <div className="selecao-qtdjogos-0">
                { this.props.jogos }
            </div>
            <div className="selecao-qtdvitorias-5">
                { this.props.vitorias }
            </div>
            <div className="selecao-qtdempates-6">
                { this.props.empates }
            </div>
            <div className="selecao-qtdderrotas-2">
                { this.props.derrotas }
            </div>
            <div className="selecao-golspro-4">
                { this.props.golsPro }
            </div>
            <div className="selecao-golscontra-2">
                { this.props.golsContra }
            </div>
            <div className="selecao-saldogols-7">
                { this.props.saldo }
            </div>
            <div className="selecao-rendimento-8">
                { this.props.porcentagem }
            </div>
        </div>
        <div className="selecao-1">
            <div className="selecao-line_2" /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}