// Generated by https://pagedraw.io/pages/10133
import React from 'react';
import Menu from './menu';
import Card_jogador from './card_jogador';
import Card_selecao from './card_selecao';
import './tela_estatisticas.css';


function render() {
    return <div className="tela_estatisticas-tela_estatisticas-1">
        <div className="tela_estatisticas-0">
            <div className="tela_estatisticas-menu_instance_5">
                <Menu img_src={this.props.logo} /> 
            </div>
        </div>
        <div className="tela_estatisticas-1">
            <div className="tela_estatisticas-card_jogador_instance-4">
                <Card_jogador card={{"tipoCard": "Artilheiro", "icone": "https://ucarecdn.com/ad831a94-cfc8-4001-bf76-1d9c0a9912fc/", "nomeJogador": "Neymar Junior", "numero": "37", "bandeira": "http://www.infoescola.com/wp-content/uploads/2011/02/bandeira-do-brasil.gif", "nomePais": "Brasil"}} /> 
            </div>
            <div className="tela_estatisticas-card_jogador_instance_2">
                <Card_jogador card={{"tipoCard": "Mais Faltoso", "icone": "https://cdn.icon-icons.com/icons2/924/PNG/512/Football_2-12_icon-icons.com_72111.png", "nomeJogador": "Ronaldo", "numero": "54", "bandeira": "http://www.infoescola.com/wp-content/uploads/2011/02/bandeira-do-brasil.gif", "nomePais": "Brasil"}} /> 
            </div>
            <div className="tela_estatisticas-card_jogador_instance_2-9">
                <Card_jogador card={{"tipoCard": "Melhor Goleiro", "icone": "https://image.freepik.com/icones-gratis/futebol-goleiro-pegar-a-bola_318-43505.jpg", "nomeJogador": "Ronaldo", "numero": "54", "bandeira": "http://www.infoescola.com/wp-content/uploads/2011/02/bandeira-do-brasil.gif", "nomePais": "Brasil"}} /> 
            </div>
        </div>
        <div className="tela_estatisticas-2">
            <div className="tela_estatisticas-card_selecao_instance-1">
                <Card_selecao cardSelecao={{"tipoCard": "Melhor Defesa", "bandeira": "http://www.infoescola.com/wp-content/uploads/2011/02/bandeira-do-brasil.gif", "nomePais": "Brasil", "numero": "10", "tipoNumero": "gols sofridos"}} /> 
            </div>
            <div className="tela_estatisticas-card_selecao_instance-3">
                <Card_selecao cardSelecao={{"tipoCard": "Melhor Ataque", "bandeira": "http://www.infoescola.com/wp-content/uploads/2011/02/bandeira-do-brasil.gif", "nomePais": "Brasil", "numero": "10", "tipoNumero": "gols feitos"}} /> 
            </div>
            <div className="tela_estatisticas-card_selecao_instance-16">
                <Card_selecao cardSelecao={{"tipoCard": "Mais Cartões", "bandeira": "http://www.infoescola.com/wp-content/uploads/2011/02/bandeira-do-brasil.gif", "nomePais": "Brasil", "numero": "10", "tipoNumero": "cartões"}} /> 
            </div>
        </div>
        <div className="tela_estatisticas-3">
            <div className="tela_estatisticas-card_selecao_instance-36">
                <Card_selecao cardSelecao={{"tipoCard": "Menos faltas", "bandeira": "http://www.infoescola.com/wp-content/uploads/2011/02/bandeira-do-brasil.gif", "nomePais": "Brasil", "numero": "10", "tipoNumero": "faltas"}} /> 
            </div>
            <div className="tela_estatisticas-card_selecao_instance-5">
                <Card_selecao cardSelecao={{"tipoCard": "Mais Faltas", "bandeira": "http://www.infoescola.com/wp-content/uploads/2011/02/bandeira-do-brasil.gif", "nomePais": "Brasil", "numero": "10", "tipoNumero": "faltas"}} /> 
            </div>
        </div>
        <div className="tela_estatisticas-4" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
