// Generated by https://pagedraw.io/pages/10133
import React from 'react';
import Menu from './menu';
import './tela_partidas.css';


function render() {
    return <div className="tela_partidas-tela_partidas-7">
        <div className="tela_partidas-0">
            <div className="tela_partidas-menu_instance_2">
                <Menu img_src={""} /> 
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
