// Generated by https://pagedraw.io/pages/10133
import React from 'react';
import Menu from './menu';
import Grupo from './grupo';
import './tela_principal.css';


function render() {
    return <div className="tela_principal-tela_principal-3">
        <div className="tela_principal-0">
            <div className="tela_principal-menu_instance-5">
                <Menu img_src={this.props.logo} /> 
            </div>
        </div>
        <div className="tela_principal-1">
            <div className="tela_principal-rectangle_1">
                <div className="tela_principal-1-0-0">
                    <div className="tela_principal-1-0-0-0">
                        <div className="tela_principal-1-0-0-0-0">
                            { this.props.listaGrupos.map((elem, i) => {
                                return <div key={i} className="tela_principal-rectangle_2">
                                    <div className="tela_principal-1-0-0-0-0-0-0-0">
                                        <div className="tela_principal-grupo_instance-7">
                                            <Grupo numeroGrupo={elem.numeroGrupo} selecoes={elem.selecoes} /> 
                                        </div>
                                    </div>
                                </div>;
                            }) }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
