// Generated by https://pagedraw.io/pages/10133
import React from 'react';
import Menu from './menu';
import Partida from './partida';
import Jogador from './jogador';
import './tela_selecao.css';


function render() {
    return <div className="tela_selecao-tela_selecao-2">
        <div className="tela_selecao-0">
            <div className="tela_selecao-menu_instance_4">
                <Menu img_src={this.props.logo} /> 
            </div>
        </div>
        <div className="tela_selecao-1">
            <img src={this.props.bandeiraSelecao} className="tela_selecao-bandeiraselecao-0" /> 
            <div className="tela_selecao-1-1">
                <div className="tela_selecao-1-1-0">
                    <div className="tela_selecao-nomeselecao-7">
                        { this.props.nomeSelecao }
                    </div>
                </div>
            </div>
            <div className="tela_selecao-1-2" /> 
        </div>
        <div className="tela_selecao-2">
            <div className="tela_selecao-rectangle_1">
                <div className="tela_selecao-2-0-0">
                    <div className="tela_selecao-rectangle_4">
                        <div className="tela_selecao-2-0-0-0-0">
                            <div className="tela_selecao-text_4">Partidas</div>
                            <div className="tela_selecao-2-0-0-0-0-1" /> 
                        </div>
                    </div>
                </div>
                <div className="tela_selecao-2-0-1">
                    <div className="tela_selecao-2-0-1-0">
                        { this.props.listaPartidas.map((elem, i) => {
                            return <div key={i} className="tela_selecao-rectangle_5">
                                <div className="tela_selecao-2-0-1-0-0-0-0">
                                    <div className="tela_selecao-partida_instance-0">
                                        <Partida bandeiraSelecao1={(elem.bandeiraSelecao1)} golsSelecao1={(elem.golsSelecao1)} golsSelecao2={(elem.golsSelecao2)} bandeiraSelecao2={(elem.bandeiraSelecao2)} nomeSelecao2={(elem.nomeSelecao2)} dataPartida={elem.dataPartida} horaPartida={elem.horaPartida} numeroGrupo={elem.numeroGrupo} estadio={elem.estadio} cidadaPartida={elem.cidadePartida} nomeSelecao1={(elem.nomeSelecao1)} idPartida={elem.idPartida} /> 
                                    </div>
                                </div>
                            </div>;
                        }) }
                    </div>
                </div>
                <div className="tela_selecao-2-0-2" /> 
            </div>
            <div className="tela_selecao-2-1">
                <div className="tela_selecao-2-1-0">
                    <div className="tela_selecao-rectangle_4-1">
                        <div className="tela_selecao-2-1-0-0-0">
                            <div className="tela_selecao-text_4-8">Jogadores</div>
                            <div className="tela_selecao-2-1-0-0-0-1" /> 
                        </div>
                    </div>
                </div>
                <div className="tela_selecao-2-1-1">
                    <div className="tela_selecao-2-1-1-0">
                        { this.props.listaJogadores.map((elem, i) => {
                            return <div key={i} className="tela_selecao-rectangle_14">
                                <div className="tela_selecao-2-1-1-0-0-0-0">
                                    <div className="tela_selecao-jogador_instance-8">
                                        <Jogador nome={elem.nome} camisa={elem.camisa} cartoesVermelhos={elem.cartoesVermelhos} cartoesAmarelos={elem.cartoesAmarelos} gols={elem.gols} posicao={elem.posicao} /> 
                                    </div>
                                </div>
                            </div>;
                        }) }
                    </div>
                </div>
                <div className="tela_selecao-2-1-2" /> 
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
