// Generated by https://pagedraw.io/pages/10133
import React from 'react';
import Menu from './menu';
import Selecoes from './selecoes';
import Lance from './lance';
import './tela_partida.css';


function render() {
    return <div className="tela_partida-tela_partida-0">
        <div className="tela_partida-0">
            <div className="tela_partida-menu_instance_3">
                <Menu img_src={""} /> 
            </div>
        </div>
        <div className="tela_partida-1">
            <div className="tela_partida-selecoes_instance-3">
                <Selecoes /> 
            </div>
        </div>
        <div className="tela_partida-2">
            <div className="tela_partida-rectangle_8">
                <div className="tela_partida-2-0-0">
                    <div className="tela_partida-text_6">Lance a Lance</div>
                </div>
            </div>
        </div>
        <div className="tela_partida-3">
            <div className="tela_partida-lance_instance-0">
                <Lance /> 
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
