INSERT INTO estadio (id_estadio, id_cidade, nome, capacidade) VALUES (1, 1, 'Luzhniki Stadium', 61105);
INSERT INTO estadio (id_estadio, id_cidade, nome, capacidade) VALUES (2, 2, 'Ekaterinburg Arena', 60086);
INSERT INTO estadio (id_estadio, id_cidade, nome, capacidade) VALUES (3, 3, 'Saint Petersburg Stadium', 58398);
INSERT INTO estadio (id_estadio, id_cidade, nome, capacidade) VALUES (4, 4, 'Fisht Stadium', 52442);
INSERT INTO estadio (id_estadio, id_cidade, nome, capacidade) VALUES (5, 5, 'Kazan Arena', 50215);
INSERT INTO estadio (id_estadio, id_cidade, nome, capacidade) VALUES (6, 1, 'Spartak Stadium', 58552);
INSERT INTO estadio (id_estadio, id_cidade, nome, capacidade) VALUES (7, 6, 'Mordovia Arena', 65330);
INSERT INTO estadio (id_estadio, id_cidade, nome, capacidade) VALUES (8, 7, 'Kaliningrad Stadium', 61859);
INSERT INTO estadio (id_estadio, id_cidade, nome, capacidade) VALUES (9, 8, 'Samara Arena', 51613);
INSERT INTO estadio (id_estadio, id_cidade, nome, capacidade) VALUES (10, 9, 'Rostov Arena', 59257);
INSERT INTO estadio (id_estadio, id_cidade, nome, capacidade) VALUES (11, 10, 'Nizhny Novgorod Stadium', 66742);
INSERT INTO estadio (id_estadio, id_cidade, nome, capacidade) VALUES (12, 11, 'Volgograd Arena', 54704);
