INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('697','PASS','008490','Auxier','19790914','Cuba');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('698','PASS','020394','Goodnoe','19820609','Denmark');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('699','PASS','027625','Borsos','19730111','Singapore');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('700','PASS','006955','Fleisher','19810609','Angola');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('701','PASS','026271','Devino','19730508','Italy');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('702','PASS','000553','Galardi','19740919','Lithuania');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('703','PASS','027222','Gengler','19761019','Costa');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('704','PASS','009766','Delzer','19761017','Barbados');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('705','PASS','014820','Calvetti','19790625','Chad');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('706','PASS','021156','Deja','19870114','Rica');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('707','PASS','015374','Dubson','19781208','Costa');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('708','PASS','027195','Castrejon','19741110','Indonesia');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('709','PASS','019979','Costilow','19760317','Austria');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('710','PASS','031884','Feddersen','19830710','Nicaragua');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('711','PASS','021706','Albanese','19810418','Bulgaria');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('712','PASS','029788','Dubitsky','19850227','Syria');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('713','PASS','018629','Brierley','19870812','Nepal');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('714','PASS','015864','Field','19841122','Finland');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('715','PASS','019424','Boutwell','19720321','Philippines');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('716','PASS','011300','Dapas','19791103','Croatia');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('717','PASS','015376','Gillie','19700114','China');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('718','PASS','019337','Charlton','19821021','Switzerland');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('719','PASS','001575','Derickson','19850515','Argentina');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('720','PASS','020900','Buddemeyer','19810226','Estonia');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('721','PASS','014024','Gettle','19801120','Uzbekistan');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('722','PASS','010139','Bocklage','19800707','Nicaragua');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('723','PASS','030582','Dehne','19801101','Bahrain');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('724','PASS','003815','Dittus','19810801','Sweden');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('725','PASS','032655','Gehlbach','19830602','Portugal');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('726','PASS','023934','Alfandre','19740404','Estonia');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('727','PASS','009429','Bergenstock','19780610','Italy');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('728','PASS','007043','Broudy','19830927','Paraguay');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('697','RUS','Ewy');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('698','SAU','Erlwein');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('699','EGY','Cerutti');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('700','URY','Aldinger');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('701','POR','Cadwallader');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('702','ESP','Bundren');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('703','MAR','Doepke');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('704','IRN','Golojuch');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('705','FRA','Fultz');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('706','AUS','Delcine');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('707','PER','Garlington');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('708','DEN','Cartland');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('709','ARG','Diciano');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('710','ISL','Brobst');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('711','CRO','Demmy');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('712','NIG','Foks');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('713','BRA','Amici');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('714','SWI','Decarr');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('715','CRI','Bulkeley');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('716','SRB','Emelina');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('717','GER','Gardino');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('718','MEX','Feindt');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('719','SWE','Brass');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('720','KOR','Frison');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('721','BEL','Butkowski');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('722','PAN','Desrocher');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('723','TUN','Acebo');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('724','ENG','Butz');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('725','POL','Ascencio');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('726','SEN','Berschauer');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('727','COL','Corvo');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('728','JPN','Compher');
