INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('577','PASS','020284','Bernas','19860226','Thailand');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('578','PASS','030014','Christiana','19870204','Algeria');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('579','PASS','002295','Crutchley','19880113','Vietnam');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('580','PASS','028710','Alana','19781006','Georgia');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('581','PASS','027151','Botello','19841022','Armenia');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('582','PASS','026395','Fladger','19780924','Peru');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('583','PASS','027261','Fiedor','19881206','Afghanistan');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('584','PASS','016344','Cisnero','19741101','Monaco');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('585','PASS','032235','Gabrielson','19761124','Germany');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('586','PASS','023210','Etchinson','19850107','Belarus');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('587','PASS','006621','Barbarino','19700210','New');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('588','PASS','025970','Dubuc','19840203','Georgia');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('589','PASS','032128','Gongalez','19830527','Morocco');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('590','PASS','001810','Clipper','19761110','Turkey');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('591','PASS','025645','Eley','19820716','Switzerland');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('592','PASS','027165','Craun','19850821','Morocco');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('593','PASS','026141','Broks','19770110','Chile');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('594','PASS','005161','Dickun','19751108','China');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('595','PASS','020003','Bronzo','19770411','Norway');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('596','PASS','013485','Blakeborough','19760418','Luxembourg');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('597','PASS','002140','Bellar','19880203','Costa');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('598','PASS','012735','Breden','19820714','Peru');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('599','PASS','005389','Ennist','19730225','Denmark');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('600','PASS','014329','Blackston','19820407','Cuba');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('601','PASS','011128','Ferm','19810303','Barbados');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('602','PASS','027667','Bacak','19710510','Zealand');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('603','PASS','015862','Deshong','19830516','Ukraine');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('604','PASS','028672','Chenette','19820526','Afghanistan');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('605','PASS','029915','Elazegui','19721111','Bahrain');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('606','PASS','016038','Debrock','19821212','Iran');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('607','PASS','029726','Fotopoulos','19890624','Rica');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('608','PASS','020216','Ahlborn','19740226','Mongolia');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('609','PASS','018494','Fredricka','19850823','Angola');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('610','PASS','006048','Borkholder','19730608','Uruguay');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('611','PASS','026350','Chua','19760905','Azerbaijan');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('612','PASS','000377','Flatley','19860717','Iraq');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('613','PASS','004985','Gerich','19870807','Philippines');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('614','PASS','005775','Coxum','19851224','Nepal');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('615','PASS','007639','Estep','19710205','Thailand');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('616','PASS','006190','Bostelman','19880311','Sweden');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('617','PASS','009251','Doser','19750411','Brazil');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('618','PASS','002823','Escobedo','19760225','Monaco');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('619','PASS','013888','Alire','19810712','Costa');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('620','PASS','007549','Amrein','19731115','Australia');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('621','PASS','012353','Brashaw','19891224','Barbados');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('622','PASS','025636','Flenard','19760914','France');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('623','PASS','016448','Felch','19800502','New');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('624','PASS','029846','Branam','19820113','Angola');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('625','PASS','006860','Beucke','19841106','Iraq');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('626','PASS','001813','Cleckley','19710422','Paraguay');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('627','PASS','012280','Abasta','19740121','Rica');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('628','PASS','003198','Cuozzo','19820622','Georgia');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('629','PASS','021788','Alm','19820808','Chile');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('630','PASS','021389','Chiem','19840616','Italy');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('631','PASS','015347','Batton','19750617','Greece');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('632','PASS','005943','Cherny','19711115','Spain');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('633','PASS','030487','Ferdon','19740217','Germany');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('634','PASS','014659','Brisky','19701219','Albania');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('635','PASS','011960','Delaune','19880407','Hungary');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('636','PASS','017855','Balde','19700113','Luxembourg');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('637','PASS','025188','Glassco','19840907','Nepal');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('638','PASS','017933','Cauthen','19870608','Costa');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('639','PASS','026754','Adamek','19700805','Estonia');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('640','PASS','002452','Castrillo','19871022','Romania');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('641','PASS','005015','Corrga','19700814','Uzbekistan');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('642','PASS','011736','Ballester','19870919','Egypt');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('643','PASS','028622','Core','19870105','Slovakia');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('644','PASS','022794','Fuerst','19801102','Afghanistan');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('645','PASS','023071','Grinde','19741222','India');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('646','PASS','008100','Fodor','19840421','Chile');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('647','PASS','012531','Balcitis','19811014','Syria');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('648','PASS','006209','December','19781211','Angola');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('649','PASS','002530','Aguillar','19710608','Morocco');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('650','PASS','025674','Eggink','19850818','Singapore');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('651','PASS','003123','Brits','19841014','Georgia');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('652','PASS','002150','Aerni','19740309','Costa');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('653','PASS','024701','Dilaura','19870523','Vietnam');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('654','PASS','031395','Gisi','19830506','Turkey');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('655','PASS','006823','Baccus','19780724','Austria');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('656','PASS','024638','Crudup','19810720','Ukraine');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('657','PASS','008090','Bidwell','19801127','Senegal');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('658','PASS','005058','Albani','19880715','Netherlands');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('659','PASS','022249','Deitsch','19800312','Barbados');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('660','PASS','018213','Arquitt','19700709','Japan');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('661','PASS','014077','Draeger','19710513','Australia');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('662','PASS','030388','Bverger','19830509','New');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('663','PASS','030144','Cacatian','19880723','France');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('664','PASS','008383','Dratch','19750222','Luxembourg');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('665','PASS','005041','Bruce','19820524','France');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('666','PASS','022151','Cardone','19741106','India');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('667','PASS','017699','Demicco','19880916','Cuba');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('668','PASS','021424','Adelaide','19860208','Cuba');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('669','PASS','016952','Drawy','19860721','Belgium');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('670','PASS','026721','Chris','19740915','Paraguay');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('671','PASS','028432','Crothers','19770417','Vietnam');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('672','PASS','005881','Abati','19810106','Hungary');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('673','PASS','019217','Englehardt','19840220','Japan');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('674','PASS','014935','Gran','19870715','Spain');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('675','PASS','001041','Digby','19880724','Thailand');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('676','PASS','023592','Constantino','19730222','Ukraine');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('677','PASS','011763','Batchelder','19831226','Angola');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('678','PASS','022195','Esterline','19840420','Luxembourg');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('679','PASS','027782','Eastep','19751007','Belarus');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('680','PASS','022166','Goodridge','19711222','France');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('681','PASS','005920','Cleverly','19820316','France');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('682','PASS','015907','Bredin','19791125','Estonia');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('683','PASS','004961','Goldston','19761222','Denmark');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('684','PASS','019080','Chainey','19871105','Croatia');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('685','PASS','005842','Booty','19741112','Morocco');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('686','PASS','019026','Didier','19720321','Finland');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('687','PASS','021033','Becke','19780411','Azerbaijan');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('688','PASS','030393','Clas','19770805','Costa');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('689','PASS','000269','Bagby','19790113','Mongolia');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('690','PASS','001927','Geddie','19750116','Netherlands');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('691','PASS','022990','Calderwood','19850124','Paraguay');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('692','PASS','024056','Clavelle','19770718','Iraq');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('693','PASS','003148','Bertovich','19860213','Albania');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('694','PASS','024192','Glidden','19780707','Brazil');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('695','PASS','005517','Etters','19770118','Georgia');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('696','PASS','029648','Albrekht','19701006','Argentina');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('577','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('578','Bandeirinha');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('579','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('580','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('581','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('582','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('583','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('584','Bandeirinha');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('585','Bandeirinha');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('586','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('587','Bandeirinha');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('588','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('589','Bandeirinha');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('590','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('591','Bandeirinha');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('592','Bandeirinha');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('593','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('594','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('595','Bandeirinha');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('596','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('597','Bandeirinha');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('598','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('599','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('600','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('601','Bandeirinha');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('602','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('603','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('604','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('605','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('606','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('607','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('608','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('609','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('610','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('611','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('612','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('613','Bandeirinha');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('614','Bandeirinha');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('615','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('616','Bandeirinha');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('617','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('618','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('619','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('620','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('621','Bandeirinha');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('622','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('623','Bandeirinha');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('624','Bandeirinha');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('625','Bandeirinha');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('626','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('627','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('628','Bandeirinha');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('629','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('630','Bandeirinha');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('631','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('632','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('633','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('634','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('635','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('636','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('637','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('638','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('639','Bandeirinha');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('640','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('641','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('642','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('643','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('644','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('645','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('646','Bandeirinha');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('647','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('648','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('649','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('650','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('651','Bandeirinha');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('652','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('653','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('654','Bandeirinha');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('655','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('656','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('657','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('658','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('659','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('660','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('661','Bandeirinha');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('662','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('663','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('664','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('665','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('666','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('667','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('668','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('669','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('670','Bandeirinha');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('671','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('672','Bandeirinha');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('673','Bandeirinha');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('674','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('675','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('676','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('677','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('678','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('679','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('680','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('681','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('682','Bandeirinha');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('683','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('684','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('685','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('686','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('687','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('688','Bandeirinha');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('689','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('690','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('691','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('692','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('693','Juiz');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('694','Bandeirinha');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('695','Bandeirinha');
INSERT INTO juiz (id_pessoa,posicao) VALUES ('696','Juiz');
