start transaction;
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (1,'RUS','Igor Akinfeev','Legia','Volante',1);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (2,'RUS','Igor Smolnikov','Dynamo','Zagueiro',2 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (3,'RUS','Viktor Vasin','Moscow','Atacante',3 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (4,'RUS','Mário Fernandes','Ajax','Meio-campo',4);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (5,'RUS','Fedor Kudrayashov','Paris','Goleiro',5);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (6,'RUS','Ilya Kutepov','Basel','Zagueiro',6);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (7,'RUS','Dmitri Kombarov','Astana','Lateral',7 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (8,'RUS','Aleksei Miranchuk','Prague','Lateral',8 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (9,'RUS','Denis Glushakov','Legia','Zagueiro',9 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (10,'RUS','Aleksandr Golovin','Warsaw','Volante',10 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (11,'RUS','Yuri Zhirkov','Young','Lateral',11 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (12,'RUS','Aleksandr Erokhin','Feyenoord','Volante',12);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (13,'RUS','Alan Dzagoev','Porto','Volante',13 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (14,'RUS','Daler Kuzyayev','Viitorul','Goleiro',14);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (15,'RUS','Daler Kuzyayev','United','Lateral',15);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (16,'RUS','Dmitry Poloz','Spartak','Zagueiro',16);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (17,'RUS','Fedor Smolov','FF','Lateral',17);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (18,'RUS','Aleksandr Kokorin','United','Meio-campo',18);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (19,'SAU','Abdullah Al-Mayouf','Moscow','Volante',1 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (20,'SAU','Osama Hawsawi','Juventus','Atacante',2 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (21,'SAU','Abdullah Al-Zori','Kyiv','Atacante',3);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (22,'SAU','Mansour Al-Harbi','Porto','Lateral',4);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (23,'SAU','Omar Hawsawi','Sevilla','Goleiro',5);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (24,'SAU','Yasser Al-Shahrani','Constanța','Meio-campo',6 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (25,'SAU','Motaz Hawsawi','Basel','Lateral',7 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (26,'SAU','Mohammed Al-Beraik','City','Meio-campo',8);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (27,'SAU','Taisir Al-Jassim','Spartak','Volante',9);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (28,'SAU','Salman Al-Faraj','Samtredia','Volante',10);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (29,'SAU','Abdulmalek Al-Khaibri','Hotspur','Volante',11);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (30,'SAU','Salman Al-Moasher','Madrid','Meio-campo',12);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (31,'SAU','Yahya Al-Shehri','Legia','Atacante',13 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (32,'SAU','Salem Al-Dosari','Ajax','Goleiro',14 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (33,'SAU','Nawaf Al-Abed','Munich','Zagueiro',15);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (34,'SAU','Mohammad Al-Sahlawi','Celtic','Volante',16 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (35,'SAU','Nasser Al-Shamrani','Brugge','Lateral',17);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (36,'SAU','Fahad Al-Muwallad','Celtic','Volante',18 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (37,'EGY','Essam El Hadary','Basel','Meio-campo',1);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (38,'EGY','Ali Gabr','Malmö','Zagueiro',2 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (39,'EGY','Ahmed Elmohamady','Celtic','Atacante',3);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (40,'EGY','Omar Gaber','Manchester','Zagueiro',4);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (41,'EGY','Ramy Rabia','Tottenham','Goleiro',5);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (42,'EGY','Ahmed Hegazi','Madrid','Meio-campo',6);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (43,'EGY','Ahmed Abdelmonem Fathy','Ludogorets','Atacante',7);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (44,'EGY','Mohamed Abdel Shaly','Liverpool','Atacante',8);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (45,'EGY','Saad El-Din Samir','Feyenoord','Lateral',9 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (46,'EGY','Tarek Hamed','Celtic','Lateral',10 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (47,'EGY','Mahmoud Kahraba','Slavia','Lateral',11 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (48,'EGY','Mohamed Elneny','Atlético','Atacante',12 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (49,'EGY','Trezeguet','Rijeka','Lateral',13 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (50,'EGY','Abdallah El Said','Liverpool','Goleiro',14 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (51,'EGY','Ramadan Sobhi','Boys','Meio-campo',15);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (52,'EGY','Ahmed Hassan','Spartak','Volante',16 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (53,'EGY','Mohamed Salah','Olympiacos','Lateral',17 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (54,'EGY','Amr Gamal','Constanța','Zagueiro',18 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (55,'URY','Fernando Muslera','Rijeka','Meio-campo',1);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (56,'URY','Maxi Pereira','Feyenoord','Zagueiro',2 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (57,'URY','Diego Godín','Prague','Lateral',3);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (58,'URY','Martín Cáceres','Liverpool','Lateral',4);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (59,'URY','José Giménez','United','Goleiro',5 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (60,'URY','Sebastián Coates','Astana','Atacante',6);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (61,'URY','Gastón Silva','Sevilla','Zagueiro',7 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (62,'URY','Mathías Corujo','Olympiacos','Volante',8 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (63,'URY','Egidio Arévalo Ríos','Liverpool','Volante',9 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (64,'URY','Álvaro González','Paris','Lateral',10);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (65,'URY','Nicolás Lodeiro','Celtic','Lateral',11 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (66,'URY','Carlos Sánchez','Young','Zagueiro',12);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (67,'URY','Cristian Rodríguez','Juventus','Zagueiro',13 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (68,'URY','Matías Vecino','Sporting','Goleiro',14 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (69,'URY','Edinson Cavani','Moscow','Volante',15);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (70,'URY','Luis Suárez','Real','Zagueiro',16);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (71,'URY','Cristhian Stuani','Legia','Atacante',17);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (72,'URY','Diego Rolán','Munich','Zagueiro',18);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (73,'POR','Rui Patrício','Hotspur','Lateral',1);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (74,'POR','Bruno Alves','Hotspur','Volante',2 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (75,'POR','Pepe','Hotspur','Volante',3);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (76,'POR','José Fonte','Porto','Meio-campo',4 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (77,'POR','Eliseu','Astana','Goleiro',5 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (78,'POR','Cédric','Madrid','Atacante',6);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (79,'POR','Raphaël Guerreiro','Atlético','Lateral',7);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (80,'POR','João Moutinho','Brugge','Volante',8);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (81,'POR','João Mário','Malmö','Lateral',9);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (82,'POR','Danilo Pereira','CSKA','Meio-campo',10 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (83,'POR','William Carvalho','Spartak','Zagueiro',11);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (84,'POR','André Gomes','Legia','Volante',12);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (85,'POR','Ricardo Quaresma','Barcelona','Zagueiro',13);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (86,'POR','Bernardo Silva','Madrid','Goleiro',14);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (87,'POR','André Silva','Sporting','Volante',15 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (88,'POR','Gelson Martins','Ludogorets','Meio-campo',16 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (89,'POR','Cristiano Ronaldo','Astana','Lateral',17 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (90,'POR','Nani','Chelsea','Zagueiro',18);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (91,'ESP','David de Gea','Legia','Lateral',1);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (92,'ESP','Jordi Alba','Sporting','Zagueiro',2);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (93,'ESP','Nacho','Malmö','Lateral',3 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (94,'ESP','Nacho Monreal','Ludogorets','Atacante',4 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (95,'ESP','Gerard Piqué','Spartak','Goleiro',5);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (96,'ESP','Sergio Ramos','Dynamo','Lateral',6 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (97,'ESP','Daniel Carvajal','Dynamo','Meio-campo',7 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (98,'ESP','Sergio Buesquets','Razgrad','Meio-campo',8 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (99,'ESP','Thiago','Brugge','Zagueiro',9);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (100,'ESP','Isco','Brugge','Volante',10 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (101,'ESP','Koke','Juventus','Meio-campo',11);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (102,'ESP','Marco Asensio','Partizan','Meio-campo',12 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (103,'ESP','Andrés Iniesta','Constanța','Volante',13);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (104,'ESP','David Silva','United','Goleiro',14);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (105,'ESP','Saúl Ñíguez','Manchester','Volante',15);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (106,'ESP','Álvaro Morata','Saint-Germain','Atacante',16);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (107,'ESP','Vitolo','Madrid','Lateral',17 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (108,'ESP','Diego Costa','Kyiv','Lateral',18);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (109,'MAR','Munir Mohamedi','Real','Atacante',1 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (110,'MAR','Medhi Benatia','Moscow','Lateral',2 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (111,'MAR','Nabil Dirar','Ludogorets','Meio-campo',3);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (112,'MAR','Romain Saïss','Sporting','Meio-campo',4 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (113,'MAR','Fouad Chafik','Samtredia','Goleiro',5 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (114,'MAR','Hamza Mendyl','Madrid','Atacante',6 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (115,'MAR','Achraf Hakimi','Chelsea','Zagueiro',7 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (116,'MAR','Mbark Boussoufa','Kyiv','Meio-campo',8);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (117,'MAR','Karim El Ahmadi','Partizan','Meio-campo',9);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (118,'MAR','Younès Belhanda','Boys','Atacante',10 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (119,'MAR','Nordin Amrabat','Porto','Meio-campo',11 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (120,'MAR','Fayçal Fajr','Real','Meio-campo',12 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (121,'MAR','Hakim Ziyech','Spartak','Zagueiro',13 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (122,'MAR','Youssef Aït Bennasser','Malmö','Goleiro',14 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (123,'MAR','Khalid Boutaib','Ludogorets','Lateral',15 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (124,'MAR','Rachid Alioui','Rijeka','Meio-campo',16 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (125,'MAR','Aziz Bouhaddouz','Madrid','Volante',17);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (126,'MAR','Youssef En-Nesyri','Sevilla','Volante',18 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (127,'IRN','Alireza Beiranvand','Brugge','Volante',1);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (128,'IRN','Pejman Montazeri','Brugge','Atacante',2 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (129,'IRN','Vouria Ghafouri','Celtic','Volante',3 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (130,'IRN','Jalal Hosseini','Atlético','Lateral',4);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (131,'IRN','Milad Mohammadi','Bayern','Goleiro',5 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (132,'IRN','Morteza Pouraliganji','Brugge','Lateral',6);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (133,'IRN','Ramin Rezaeian','City','Volante',7);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (134,'IRN','Ehsan Hajsafi','Dynamo','Volante',8 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (135,'IRN','Omid Ebrahimi','Barcelona','Meio-campo',9 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (136,'IRN','Saeid Ezatolahi','Malmö','Volante',10 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (137,'IRN','Vahid Amiri','Young','Zagueiro',11);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (138,'IRN','Alireza Jahanbakhsh','Constanța','Atacante',12);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (139,'IRN','Ashkan Dejagah','Warsaw','Atacante',13);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (140,'IRN','Saman Ghoddos','Munich','Goleiro',14);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (141,'IRN','Mehdi Taremi','Moscow','Meio-campo',15);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (142,'IRN','Karim Ansarifard','Sevilla','Lateral',16);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (143,'IRN','Reza Ghoochannejhad','United','Atacante',17 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (144,'IRN','Sardar Azmoun','Hotspur','Lateral',18 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (145,'FRA','Hugo Lloris','Warsaw','Atacante',1);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (146,'FRA','Raphaël Varane','CP','Volante',2);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (147,'FRA','Lucas Digne','Real','Zagueiro',3);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (148,'FRA','Djibril Sidibé','Porto','Atacante',4);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (149,'FRA','Samuel Umtiti','City','Goleiro',5 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (150,'FRA','Layvin Kurzawa','Brugge','Lateral',6);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (151,'FRA','Laurent Koscielny','Rijeka','Zagueiro',7);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (152,'FRA','Balise Matuidi','Liverpool','Volante',8 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (153,'FRA','N’Golo Kanté','Kyiv','Volante',9);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (154,'FRA','Thomas Lemar','Kyiv','Meio-campo',10);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (155,'FRA','Adrien Rabiot','Slavia','Volante',11);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (156,'FRA','Paul Pogba','Hotspur','Volante',12);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (157,'FRA','Olivier Giroud','Viitorul','Atacante',13);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (158,'FRA','Antoine Griezmann','Feyenoord','Goleiro',14 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (159,'FRA','Alexandre Lacazette','United','Atacante',15 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (160,'FRA','Kylian Mbappé','Slavia','Atacante',16 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (161,'FRA','Ousmane Dembélé','Spartak','Volante',17 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (162,'FRA','Anthony Martial','CP','Zagueiro',18 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (163,'AUS','Mathew Ryan','Dynamo','Atacante',1);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (164,'AUS','Mitchell Langerak','Legia','Volante',2);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (165,'AUS','Milos Degenek','Astana','Zagueiro',3);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (166,'AUS','Bailey Wright','Spartak','Meio-campo',4 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (167,'AUS','Aziz Behich','Rijeka','Goleiro',5 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (168,'AUS','Trent Sainsbury','Liverpool','Atacante',6 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (169,'AUS','Ryan McGowan','Malmö','Volante',7 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (170,'AUS','Mark Milligan','Olympiacos','Atacante',8);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (171,'AUS','Aaron Mooy','Boys','Lateral',9);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (172,'AUS','James Troisi','Razgrad','Meio-campo',10 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (173,'AUS','Mile Jedinak','Astana','Volante',11 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (174,'AUS','Massimo Luongo','Munich','Lateral',12 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (175,'AUS','Jackson Irvine','Barcelona','Meio-campo',13 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (176,'AUS','Tom Rogic','Viitorul','Goleiro',14);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (177,'AUS','Tim Cahill','Barcelona','Atacante',15 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (178,'AUS','Mathew Leckie','Basel','Lateral',16 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (179,'AUS','Tomi Juric','Munich','Lateral',17 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (180,'AUS','Robbie Kruse','Young','Meio-campo',18 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (181,'PER','Pedro Gallese','Saint-Germain','Zagueiro',1 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (182,'PER','Carlos Cáceda','Kyiv','Meio-campo',2);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (183,'PER','Aldo Corzo','Paris','Meio-campo',3);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (184,'PER','Miguel Trauco','Viitorul','Zagueiro',4);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (185,'PER','Christian Ramos','Saint-Germain','Goleiro',5);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (186,'PER','Luis Advincula','Tottenham','Lateral',6 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (187,'PER','Alberto Rodríguez','Atlético','Lateral',7 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (188,'PER','Miguel Araujo','Viitorul','Lateral',8 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (189,'PER','Christian Cueva','Samtredia','Lateral',9);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (190,'PER','Renato Tapia','Sevilla','Atacante',10 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (191,'PER','Andy Polo','City','Zagueiro',11 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (192,'PER','Yoshimar Yotún','Real','Meio-campo',12);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (193,'PER','Edison Flores','Munich','Atacante',13 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (194,'PER','Paolo Hurtado','Madrid','Goleiro',14);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (195,'PER','Paolo Guerrero','Warsaw','Atacante',15);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (196,'PER','Jefferson Farfán','Porto','Atacante',16 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (197,'PER','Raúl Ruidíaz','Feyenoord','Zagueiro',17 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (198,'PER','André Carrillo','Astana','Atacante',18);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (199,'DEN','Kasper Schmeichel','Young','Meio-campo',1 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (200,'DEN','Kannik Vestergaard','Sporting','Volante',2);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (201,'DEN','Simon Kjaer','Spartak','Meio-campo',3 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (202,'DEN','Andreas Christensen','Boys','Zagueiro',4);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (203,'DEN','Andreas Bjelland','Atlético','Goleiro',5);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (204,'DEN','Mathias Jorgensen','Legia','Volante',6);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (205,'DEN','Jens Stryger Larsen','CP','Volante',7 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (206,'DEN','Peter Ankersen','Basel','Atacante',8);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (207,'DEN','Riza Durmisi','Sporting','Atacante',9 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (208,'DEN','William Kvist','Sporting','Volante',10);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (209,'DEN','Thomas Delaney','Madrid','Meio-campo',11);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (210,'DEN','Christian Eriksen','Manchester','Volante',12);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (211,'DEN','Lasse Schöne','FF','Meio-campo',13);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (212,'DEN','Pione Sisto','Prague','Goleiro',14);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (213,'DEN','Nicklas Bendtner','Liverpool','Zagueiro',15 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (214,'DEN','Nicolai Jorgensen','Saint-Germain','Meio-campo',16);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (215,'DEN','Yussuf Poulsen','Warsaw','Zagueiro',17);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (216,'DEN','Andreas Cornelius','Chelsea','Zagueiro',18);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (217,'ARG','Sergio Romero','Saint-Germain','Volante',1);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (218,'ARG','Gabriel Mercado','Chelsea','Atacante',2 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (219,'ARG','Federico Fazio','Prague','Zagueiro',3 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (220,'ARG','Javier Mascherano','Partizan','Atacante',4);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (221,'ARG','Nicolás Otamendi','Liverpool','Goleiro',5 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (222,'ARG','Marcos Rojo','Sevilla','Lateral',6);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (223,'ARG','Ramiro Funes Mori','Moscow','Meio-campo',7);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (224,'ARG','Lucas Biglia','Viitorul','Zagueiro',8 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (225,'ARG','Enzo Pérez','Partizan','Zagueiro',9 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (226,'ARG','Ángel Di Maria','Moscow','Volante',10 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (227,'ARG','Marcos Acuña','Warsaw','Volante',11 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (228,'ARG','Éver Banega','Young','Atacante',12);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (229,'ARG','Eduardo Salvio','Real','Volante',13 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (230,'ARG','Mauro Icardi','Manchester','Goleiro',14 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (231,'ARG','Lionel Messi','Saint-Germain','Atacante',15 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (232,'ARG','Paulo Dybala','Manchester','Zagueiro',16);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (233,'ARG','Sergio Agüero','Kyiv','Meio-campo',17 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (234,'ARG','Gonzalo Higuaín','City','Zagueiro',18 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (235,'ISL','Hannes Halldórsson','Malmö','Volante',1 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (236,'ISL','Birkir Saevarsson','Kyiv','Zagueiro',2);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (237,'ISL','Ragnar Sigurdsson','Celtic','Atacante',3);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (238,'ISL','Kári Árnason','Astana','Atacante',4 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (239,'ISL','Ari Skúlason','Moscow','Goleiro',5);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (240,'ISL','Sverrir Ingason','CP','Lateral',6 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (241,'ISL','Hordur Magnússon','Samtredia','Meio-campo',7);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (242,'ISL','Aron Gunnarsson','Chelsea','Lateral',8);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (243,'ISL','Birkir Bjarnason','Munich','Meio-campo',9 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (244,'ISL','Emil Hallfredsson','Partizan','Lateral',10);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (245,'ISL','Gylfi Sigurdsson','Dynamo','Meio-campo',11);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (246,'ISL','Arnór Ingvi Traustason','Basel','Atacante',12 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (247,'ISL','Rúrik Gíslason','Chelsea','Zagueiro',13 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (248,'ISL','Johann Gudmundsson','Boys','Goleiro',14 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (249,'ISL','Alfred Finnbogason','Manchester','Lateral',15 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (250,'ISL','Jón Dadi Bödvarsson','Manchester','Volante',16);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (251,'ISL','Vidar Örn Kjartansson','Manchester','Zagueiro',17);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (252,'ISL','Björn Sigurdarson','Slavia','Volante',18);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (253,'CRO','Danijel Subasic','Partizan','Meio-campo',1);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (254,'CRO','Sime Vrsaljko','Basel','Atacante',2 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (255,'CRO','Ivan Strinic','Viitorul','Lateral',3);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (256,'CRO','Dejan Lovren','Bayern','Volante',4);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (257,'CRO','Domagoj Vida','Prague','Goleiro',5);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (258,'CRO','Josip Pivaric','Sporting','Zagueiro',6);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (259,'CRO','Vedran Corluka','Prague','Atacante',7 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (260,'CRO','Ivan Rakitic','Ajax','Meio-campo',8 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (261,'CRO','Luka Modric','Manchester','Volante',9 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (262,'CRO','Marcelo Brozovic','Paris','Meio-campo',10 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (263,'CRO','Marko Rog','Malmö','Volante',11 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (264,'CRO','Mario Pasalic','City','Zagueiro',12 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (265,'CRO','Milan Badelj','CP','Atacante',13);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (266,'CRO','Mateo Kovacic','Manchester','Goleiro',14);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (267,'CRO','Andrej Kramaric','Chelsea','Lateral',15 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (268,'CRO','Nikola Kalinic','CSKA','Lateral',16 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (269,'CRO','Mario Mandzukic','City','Lateral',17);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (270,'CRO','Ivan Perisic','City','Volante',18 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (271,'NIG','Ikechukwu Ezenwa','Porto','Zagueiro',1);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (272,'NIG','Elderson Echiejilé','Celtic','Atacante',2 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (273,'NIG','Shehu Abdullahi','Brugge','Meio-campo',3);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (274,'NIG','William Troost-Ekong','Celtic','Lateral',4);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (275,'NIG','Leon Balogun','Paris','Goleiro',5 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (276,'NIG','Kenneth Omeruo','Olympiacos','Zagueiro',6 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (277,'NIG','Ola Aina','Saint-Germain','Meio-campo',7);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (278,'NIG','John Obi Mikel','Ajax','Zagueiro',8 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (279,'NIG','Ogenyi Onazi','Hotspur','Volante',9 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (280,'NIG','Etebo Oghenekaro','Real','Meio-campo',10);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (281,'NIG','Wilfred Ndidi','Rijeka','Meio-campo',11 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (282,'NIG','Mikel Agu','Manchester','Volante',12);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (283,'NIG','Ahmed Musa','Sporting','Volante',13 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (284,'NIG','Victor Musa','Atlético','Goleiro',14);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (285,'NIG','Moses Simon','Saint-Germain','Volante',15 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (286,'NIG','Odion Ighalo','Madrid','Zagueiro',16);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (287,'NIG','Alex Iwobi','Manchester','Meio-campo',17);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (288,'NIG','Kelechi Iheanacho','Partizan','Atacante',18 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (289,'BRA','Alisson','Barcelona','Zagueiro',1 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (290,'BRA','Dani Alves','City','Atacante',2 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (291,'BRA','Thiago Silva','Kyiv','Lateral',3);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (292,'BRA','Miranda','Sevilla','Zagueiro',4 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (293,'BRA','Filipe Luís','Liverpool','Goleiro',5);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (294,'BRA','Marquinhos','Kyiv','Lateral',6);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (295,'BRA','Marcelo','Munich','Lateral',7 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (296,'BRA','Willian','Hotspur','Lateral',8);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (297,'BRA','Paulinho','Hotspur','Volante',9 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (298,'BRA','Fernandinho','United','Atacante',10 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (299,'BRA','Casemiro','City','Lateral',11 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (300,'BRA','Renato Augusto','Sevilla','Volante',12);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (301,'BRA','Giuliano','Paris','Volante',13);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (302,'BRA','Philippe Coutinho','Malmö','Goleiro',14 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (303,'BRA','Douglas Costa','Kyiv','Lateral',15);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (304,'BRA','Roberto Firmino','Liverpool','Atacante',16);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (305,'BRA','Gabriel Jesus','Olympiacos','Zagueiro',17 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (306,'BRA','Neymar Jr','Madrid','Volante',18);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (307,'SWI','Yann Sommer','Malmö','Zagueiro',1 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (308,'SWI','Stephan Lichtsteiner','Porto','Volante',2 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (309,'SWI','Manuel Akanji','Dynamo','Atacante',3);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (310,'SWI','Michael Lang','Feyenoord','Volante',4 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (311,'SWI','Ricardo Rodríguez','Hotspur','Goleiro',5);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (312,'SWI','Johan Djourou','Moscow','Volante',6 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (313,'SWI','Fabian Schär','Saint-Germain','Volante',7 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (314,'SWI','Granit Xhaka','Constanța','Lateral',8 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (315,'SWI','Steven Zuber','Kyiv','Volante',9);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (316,'SWI','Blerim Dzemaili','Ludogorets','Zagueiro',10 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (317,'SWI','Denis Zakaria','Brugge','Meio-campo',11 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (318,'SWI','Xherdan Shaqiri','Warsaw','Atacante',12 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (319,'SWI','Valon Behrami','City','Lateral',13);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (320,'SWI','Gerson Fernandes','CP','Goleiro',14 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (321,'SWI','Breel Embolo','Madrid','Zagueiro',15);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (322,'SWI','Haris Seferovic','United','Zagueiro',16 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (323,'SWI','Admir Mehmedi','Slavia','Atacante',17 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (324,'SWI','Eren Derdiyok','Barcelona','Meio-campo',18);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (325,'CRI','Keylor Navas','Real','Meio-campo',1 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (326,'CRI','Giancarlo González','Olympiacos','Lateral',2);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (327,'CRI','Cristian Gamboa','Partizan','Atacante',3);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (328,'CRI','Bryan Oviedo','Boys','Atacante',4 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (329,'CRI','Francisco Calvo','Tottenham','Goleiro',5);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (330,'CRI','Kendall Waston','Partizan','Lateral',6);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (331,'CRI','Rónald Matarrita','Barcelona','Volante',7 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (332,'CRI','Michael Umaña','Ludogorets','Lateral',8 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (333,'CRI','Johnny Acosta','Real','Meio-campo',9);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (334,'CRI','Bryan Ruiz','Legia','Zagueiro',10 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (335,'CRI','Celso Borges','Barcelona','Volante',11);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (336,'CRI','Christian Bolaños','Paris','Lateral',12 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (337,'CRI','Randall Azofeifa','Prague','Atacante',13);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (338,'CRI','David Guzmán','Ajax','Goleiro',14 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (339,'CRI','Rodney Wallace','Chelsea','Meio-campo',15 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (340,'CRI','Joel Campbell','Malmö','Meio-campo',16);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (341,'CRI','Marco Ureña','Celtic','Meio-campo',17 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (342,'CRI','Johan Venegas','CP','Volante',18);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (343,'SRB','Vladimir Stojkovic','Spartak','Zagueiro',1);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (344,'SRB','Branislav Ivanovic','Juventus','Volante',2);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (345,'SRB','Aleksandar Kolarov','Paris','Zagueiro',3);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (346,'SRB','Antonio Rukavina','Moscow','Lateral',4);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (347,'SRB','Matija Nastasic','Celtic','Goleiro',5 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (348,'SRB','Dusko Tosic','Brugge','Zagueiro',6);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (349,'SRB','Nikola Maksimovic','Celtic','Volante',7 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (350,'SRB','Jagos Vukovic','Rijeka','Zagueiro',8);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (351,'SRB','Dusan Tadic','Astana','Meio-campo',9);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (352,'SRB','Sergej Milinkovic-Savic','Basel','Lateral',10 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (353,'SRB','Nemanja Matic','Celtic','Atacante',11 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (354,'SRB','Luka Milivojevic','Atlético','Zagueiro',12);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (355,'SRB','Adem Ljajic','Madrid','Volante',13);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (356,'SRB','Nemanja Gudelj','Barcelona','Goleiro',14);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (357,'SRB','Mijat Gacinovic','Basel','Lateral',15 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (358,'SRB','Filip Kostic','Porto','Atacante',16 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (359,'SRB','Aleksandar Mitrovic','CP','Meio-campo',17 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (360,'SRB','Aleksandar Prijovic','Warsaw','Volante',18);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (361,'GER','Manuel Neuer','Razgrad','Lateral',1 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (362,'GER','Mats Hummels','City','Volante',2);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (363,'GER','Antonio Rüdiger','Juventus','Lateral',3 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (364,'GER','Jérôme Boateng','Olympiacos','Zagueiro',4 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (365,'GER','Joshua Kimmich','Saint-Germain','Goleiro',5 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (366,'GER','Jonas Hector','Sporting','Lateral',6);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (367,'GER','Julian Draxler','Prague','Zagueiro',7 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (368,'GER','Toni Kroos','Constanța','Meio-campo',8);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (369,'GER','Emre Can','Warsaw','Atacante',9 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (370,'GER','Leon Goretzka','Madrid','Volante',10);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (371,'GER','Julian Brandt','Madrid','Zagueiro',11 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (372,'GER','Sebastian Rudy','Ajax','Volante',12 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (373,'GER','Leroy Sané','Dynamo','Zagueiro',13);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (374,'GER','Mesut Özil','Young','Goleiro',14);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (375,'GER','Sami Khedira','Ludogorets','Zagueiro',15);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (376,'GER','Mario Götze','Boys','Volante',16);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (377,'GER','Thomas Müller','Feyenoord','Meio-campo',17);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (378,'GER','Timo Werner','United','Meio-campo',18 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (379,'MEX','Guillermo Ochoa','Tottenham','Meio-campo',1 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (380,'MEX','Hugo Ayala','Manchester','Lateral',2);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (381,'MEX','Diego Reyes','Rijeka','Zagueiro',3);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (382,'MEX','Héctor Moreno','Basel','Volante',4);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (383,'MEX','Jesús Gallardo','Moscow','Goleiro',5);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (384,'MEX','Miguel Layún','Saint-Germain','Lateral',6 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (385,'MEX','Carlos Salcedo','Feyenoord','Meio-campo',7);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (386,'MEX','Jonathan dos Santos','Viitorul','Zagueiro',8);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (387,'MEX','Giovani dos Santos','Barcelona','Zagueiro',9);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (388,'MEX','Andrés Guardado','Rijeka','Meio-campo',10 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (389,'MEX','Héctor Herrera','Sevilla','Meio-campo',11 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (390,'MEX','Javier Aquino','FF','Atacante',12 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (391,'MEX','Jesús Corona','Ludogorets','Lateral',13 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (392,'MEX','Hirving Lozano','Basel','Goleiro',14);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (393,'MEX','Raúl Jiménez','Saint-Germain','Zagueiro',15 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (394,'MEX','Carlos Vela','Astana','Volante',16);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (395,'MEX','Javier Hernández','Malmö','Meio-campo',17 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (396,'MEX','Oribe Peralta','Moscow','Volante',18);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (397,'SWE','Robin Olsen','Moscow','Zagueiro',1);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (398,'SWE','Mikel Lustig','Rijeka','Atacante',2 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (399,'SWE','Victor Nilsson Lindelöf','Bayern','Zagueiro',3);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (400,'SWE','Andreas Granqvist','Astana','Meio-campo',4);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (401,'SWE','Martin Olsson','Spartak','Goleiro',5);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (402,'SWE','Ludwig Augustinsson','Manchester','Lateral',6 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (403,'SWE','Emil Krafth','Liverpool','Volante',7);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (404,'SWE','Pontus Jansson','Sevilla','Volante',8 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (405,'SWE','Sebastian Larsson','Boys','Zagueiro',9);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (406,'SWE','Emil Forsberg','Saint-Germain','Lateral',10 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (407,'SWE','Gustav Svensson','Porto','Meio-campo',11);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (408,'SWE','Viktor Claesson','Prague','Zagueiro',12 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (409,'SWE','Jimmy Durmaz','Moscow','Zagueiro',13);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (410,'SWE','Albin Ekdal','Bayern','Goleiro',14);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (411,'SWE','Isaac Kiese Thelin','Ajax','Meio-campo',15);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (412,'SWE','Marcus Berg','FF','Meio-campo',16 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (413,'SWE','John Guidetti','Partizan','Volante',17);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (414,'SWE','Ola Toivonen','Madrid','Meio-campo',18);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (415,'KOR','Kim Seunggyu','Razgrad','Lateral',1 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (416,'KOR','Kim Younggwon','Brugge','Volante',2 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (417,'KOR','Kim Jinsu','Atlético','Zagueiro',3);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (418,'KOR','Kwak Taehwi','United','Meio-campo',4);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (419,'KOR','Hong Jeongho','Feyenoord','Goleiro',5 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (420,'KOR','Jang Hyunsoo','Brugge','Lateral',6);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (421,'KOR','Koo Jacheol','Celtic','Atacante',7);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (422,'KOR','Kwon Changhoon','Partizan','Zagueiro',8 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (423,'KOR','Ki Sungyueng','Manchester','Meio-campo',9 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (424,'KOR','Nam Taehee','Juventus','Lateral',10 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (425,'KOR','Han Kookyoung','Constanța','Zagueiro',11);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (426,'KOR','Lee Chungyoung','Slavia','Zagueiro',12);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (427,'KOR','Jung Wooyoung','Brugge','Meio-campo',13 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (428,'KOR','Lee Jaesung','Olympiacos','Goleiro',14);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (429,'KOR','Son Heungmin','Sporting','Meio-campo',15);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (430,'KOR','Ji Dongwon','Liverpool','Atacante',16 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (431,'KOR','Kim Shinwook','Hotspur','Lateral',17);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (432,'KOR','Hwang Heechan','Samtredia','Zagueiro',18);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (433,'BEL','Thibaut Courtois','Spartak','Lateral',1 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (434,'BEL','Toby Alderweireld','City','Zagueiro',2);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (435,'BEL','Thomas Vermaelen','Barcelona','Lateral',3 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (436,'BEL','Jan Vertonghen','Razgrad','Lateral',4 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (437,'BEL','Vincent Kompany','Dynamo','Goleiro',5 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (438,'BEL','Thomas Meunier','Bayern','Atacante',6 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (439,'BEL','Axel Witsel','Warsaw','Zagueiro',7);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (440,'BEL','Radja Nainggolan','Saint-Germain','Volante',8 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (441,'BEL','Kevin De Bruyne','Malmö','Meio-campo',9 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (442,'BEL','Marouane Fellaini','Sevilla','Lateral',10 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (443,'BEL','Youri Tielemans','Tottenham','Meio-campo',11);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (444,'BEL','Mousa Dembélé','Olympiacos','Atacante',12 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (445,'BEL','Nacer Chadli','Barcelona','Lateral',13);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (446,'BEL','Eden Hazard','Paris','Goleiro',14 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (447,'BEL','Yannick Carrasco','CP','Meio-campo',15);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (448,'BEL','Dries Mertens','Bayern','Lateral',16);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (449,'BEL','Michy Batshuayi','Young','Lateral',17 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (450,'BEL','Romelu Lukaku','Basel','Atacante',18);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (451,'PAN','Jaime Penedo','Tottenham','Volante',1 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (452,'PAN','José Calderón','Young','Meio-campo',2 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (453,'PAN','Michael Murillo','Viitorul','Zagueiro',3);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (454,'PAN','Fidel Escobar','Bayern','Lateral',4 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (455,'PAN','Román Torres','CSKA','Goleiro',5);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (456,'PAN','Adolfo Machado','Legia','Zagueiro',6);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (457,'PAN','Éric Davis','City','Volante',7);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (458,'PAN','Luis Ovalle','Young','Zagueiro',8 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (459,'PAN','Felipe Baloy','Real','Volante',9);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (460,'PAN','Gabriel Gómez','Dynamo','Meio-campo',10 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (461,'PAN','Édgar Bárcenas','Porto','Lateral',11);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (462,'PAN','Armando Cooper','Chelsea','Meio-campo',12 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (463,'PAN','Alberto Quintero','Paris','Meio-campo',13 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (464,'PAN','Aníbal Godoy','Feyenoord','Goleiro',14);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (465,'PAN','Blas Pérez','Porto','Atacante',15 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (466,'PAN','Gabriel Torres','Porto','Lateral',16);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (467,'PAN','Luis Tejada','Ludogorets','Atacante',17 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (468,'PAN','Abdiel Arroyo','Juventus','Meio-campo',18 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (469,'TUN','Aymen Mathlouthi','Madrid','Meio-campo',1 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (470,'TUN','Ali Maâloul','Real','Zagueiro',2);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (471,'TUN','Syam Ben Youssef','Spartak','Meio-campo',3);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (472,'TUN','Aymen Abdennour','Real','Zagueiro',4);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (473,'TUN','Hamdi Naguez','City','Goleiro',5);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (474,'TUN','Yassine Meriah','Basel','Meio-campo',6);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (475,'TUN','Oussama Haddadi','Slavia','Meio-campo',7);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (476,'TUN','Ferjani Sassi','Madrid','Volante',8 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (477,'TUN','Wahbi Khazri','City','Atacante',9 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (478,'TUN','Mohamed Amine Ben Amor','Ludogorets','Volante',10);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (479,'TUN','Ghaylène Chaalali','Porto','Atacante',11);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (480,'TUN','Naïm Sliti','Manchester','Volante',12 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (481,'TUN','Youssef Msakni','Liverpool','Lateral',13);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (482,'TUN','Fakhreddine Ben Youssef','Moscow','Goleiro',14);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (483,'TUN','Taha Yassine Khenissi','Ajax','Atacante',15 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (484,'TUN','Yoann Touzghar','Atlético','Atacante',16);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (485,'TUN','Anice Bradi','United','Meio-campo',17 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (486,'TUN','Ahmed Akaïchi','Astana','Lateral',18);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (487,'ENG','Joe Hart','Feyenoord','Volante',1 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (488,'ENG','Jordan Pickford','Kyiv','Meio-campo',2);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (489,'ENG','Gary Cahill','Ludogorets','Atacante',3);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (490,'ENG','Kyle Walker','Sevilla','Meio-campo',4 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (491,'ENG','John Stones','Boys','Goleiro',5 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (492,'ENG','Ryan Bertrand','Manchester','Lateral',6 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (493,'ENG','Danny Rose','Dynamo','Meio-campo',7 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (494,'ENG','Phil Jones','City','Atacante',8 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (495,'ENG','Jordan Henderson','Partizan','Zagueiro',9 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (496,'ENG','Alex Oxlade-Chamberlain','Moscow','Volante',10);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (497,'ENG','Dele Alli','Moscow','Meio-campo',11 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (498,'ENG','Eric Dier','Real','Lateral',12);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (499,'ENG','Adam Lallana','Basel','Volante',13);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (500,'ENG','Jesse Lingard','Bayern','Goleiro',14);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (501,'ENG','Raheem Sterling','Barcelona','Zagueiro',15);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (502,'ENG','Harry Kane','CSKA','Atacante',16);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (503,'ENG','Marcus Rashford','Paris','Meio-campo',17);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (504,'ENG','Jamie Vardy','Viitorul','Atacante',18 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (505,'POL','Lukasz Fabianski','Kyiv','Zagueiro',1 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (506,'POL','Wojciech Szczesny','Dynamo','Atacante',2);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (507,'POL','Lukasz Piszczek','CSKA','Zagueiro',3);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (508,'POL','Kamil Glik','Madrid','Lateral',4);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (509,'POL','Michal Pazdan','Bayern','Goleiro',5 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (510,'POL','Thiago Cionek','Olympiacos','Zagueiro',6);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (511,'POL','Bartosz Bereszynski','Ludogorets','Meio-campo',7);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (512,'POL','Artur Jedrzejczyk','Brugge','Volante',8 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (513,'POL','Maciej Rybus','Viitorul','Lateral',9);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (514,'POL','Jakub Blaszczykowski','Rijeka','Meio-campo',10);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (515,'POL','Kamil Grosicki','Atlético','Lateral',11 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (516,'POL','Grzegorz Krychowiak','Celtic','Meio-campo',12 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (517,'POL','Krzysztof Maczynski','Saint-Germain','Meio-campo',13);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (518,'POL','Piotr Zielinski','Dynamo','Goleiro',14);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (519,'POL','Karol Linetty','Ajax','Zagueiro',15 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (520,'POL','Robert Lewandowski','United','Zagueiro',16);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (521,'POL','Lukasz Teodorczyk','Sporting','Lateral',17);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (522,'POL','Arkadiusz Milik','Constanța','Volante',18 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (523,'SEN','Khadim N’Diaye','Porto','Zagueiro',1);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (524,'SEN','Kara Mbodj','Spartak','Zagueiro',2);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (525,'SEN','Lamine Gassama','Slavia','Atacante',3 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (526,'SEN','Kalidou Koulibaly','Real','Meio-campo',4);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (527,'SEN','Salif Sané','Madrid','Goleiro',5);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (528,'SEN','Saliou Ciss','Partizan','Lateral',6 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (529,'SEN','Moussa Wagué','CSKA','Lateral',7);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (530,'SEN','Idrissa Gueye','Razgrad','Volante',8);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (531,'SEN','Cheikhou Kouyaté','Ajax','Atacante',9 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (532,'SEN','Cheikh Ndoye','Basel','Lateral',10);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (533,'SEN','Papa Alioune N’Diaye','Barcelona','Lateral',11);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (534,'SEN','Sadio Mané','Munich','Lateral',12 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (535,'SEN','Moussa Sow','Slavia','Lateral',13 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (536,'SEN','Moussa Konaté','Boys','Goleiro',14);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (537,'SEN','Keita Baldé','Moscow','Atacante',15 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (538,'SEN','M’Baye Niang','Celtic','Lateral',16 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (539,'SEN','Ismaïla Sarr','United','Volante',17 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (540,'SEN','Mame Diouf','United','Atacante',18);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (541,'COL','David Ospina','Madrid','Zagueiro',1 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (542,'COL','Cristian Zapata','Chelsea','Meio-campo',2 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (543,'COL','Santiago Arias','Sporting','Lateral',3);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (544,'COL','Frank Fabra','Astana','Volante',4 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (545,'COL','Dávinson Sánchez','Liverpool','Goleiro',5 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (546,'COL','Yerry Mina','Moscow','Lateral',6);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (547,'COL','Carlos Sánchez','Spartak','Meio-campo',7);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (548,'COL','Juan Guillermo Cuadrado','Chelsea','Volante',8);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (549,'COL','Abel Aguilar','Hotspur','Lateral',9 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (550,'COL','James Rodríguez','Paris','Lateral',10 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (551,'COL','Giovanni Moreno','CSKA','Atacante',11 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (552,'COL','Wílmar Barrios','Madrid','Atacante',12);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (553,'COL','Radamel Falcao García','Tottenham','Zagueiro',13);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (554,'COL','Teófilo Gutiérrez','Partizan','Goleiro',14);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (555,'COL','Carlos Bacca','Malmö','Volante',15);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (556,'COL','Edwin Cardona','Feyenoord','Zagueiro',16);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (557,'COL','Yimmi Chará','Atlético','Meio-campo',17 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (558,'COL','Duván Zapata','Legia','Volante',18);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (559,'JPN','Eiji Kawashima','Moscow','Atacante',1 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (560,'JPN','Shusaku Nishikawa','Rijeka','Meio-campo',2);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (561,'JPN','Masato Morishige','Sevilla','Atacante',3);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (562,'JPN','Yuto Nagatomo','Astana','Volante',4 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (563,'JPN','Hiroki Sakai','Moscow','Goleiro',5);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (564,'JPN','Tomoaki Makino','Olympiacos','Meio-campo',6 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (565,'JPN','Gotoku Sakai','Liverpool','Meio-campo',7);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (566,'JPN','Maya Yoshida','Munich','Atacante',8 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (567,'JPN','Hotaru Yamaguchi','Ludogorets','Lateral',9);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (568,'JPN','Shinji Kagawa','Malmö','Volante',10 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (569,'JPN','Makoto Hasebe','Constanța','Meio-campo',11);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (570,'JPN','Hiroshi Kiyotake','Sevilla','Lateral',12);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (571,'JPN','Keisuke Honda','Warsaw','Volante',13);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (572,'JPN','Takashi Usami','CP','Goleiro',14);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (573,'JPN','Genki Haraguchi','FF','Meio-campo',15 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (574,'JPN','Shinji Okazaki','Chelsea','Volante',16);
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (575,'JPN','Yuya Kubo','Ludogorets','Zagueiro',17 );
INSERT INTO jogador (id_pessoa,codigo_pais_joga,nome_conhecido,posicao,clube_origem,numero_camisa) VALUES (576,'JPN','Yuya Osako','Warsaw','Zagueiro',18);
commit;