INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (1, 1,'Snowy Excalibur Resort Moscow',507,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (2, 1,'Ruby Dome Hotel Moscow',906,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (3, 1,'Ancient Cliff Resort Moscow',605,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (4, 1,'Olive Pinnacle Hotel & Spa Moscow',987,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (5, 1,'Sunrise Park Resort Moscow',613,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (6, 1,'Western Spire Resort & Spa Moscow',552,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (7, 1,'Fantasy Resort Moscow',990,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (8, 1,'Stellar Resort Moscow',557,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (9, 1,'Harborview Hotel Moscow',998,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (10, 1,'Nimbus Hotel Moscow',888,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (11, 2,'Snowy Excalibur Resort Ekaterinburg',921,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (12, 2,'Ruby Dome Hotel Ekaterinburg',631,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (13, 2,'Ancient Cliff Resort Ekaterinburg',753,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (14, 2,'Olive Pinnacle Hotel & Spa Ekaterinburg',629,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (15, 2,'Sunrise Park Resort Ekaterinburg',809,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (16, 2,'Western Spire Resort & Spa Ekaterinburg',708,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (17, 2,'Fantasy Resort Ekaterinburg',528,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (18, 2,'Stellar Resort Ekaterinburg',841,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (19, 2,'Harborview Hotel Ekaterinburg',760,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (20, 2,'Nimbus Hotel Ekaterinburg',839,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (21, 3,'Snowy Excalibur Resort St. Petersburg',529,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (22, 3,'Ruby Dome Hotel St. Petersburg',726,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (23, 3,'Ancient Cliff Resort St. Petersburg',783,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (24, 3,'Olive Pinnacle Hotel & Spa St. Petersburg',600,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (25, 3,'Sunrise Park Resort St. Petersburg',799,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (26, 3,'Western Spire Resort & Spa St. Petersburg',536,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (27, 3,'Fantasy Resort St. Petersburg',506,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (28, 3,'Stellar Resort St. Petersburg',650,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (29, 3,'Harborview Hotel St. Petersburg',769,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (30, 3,'Nimbus Hotel St. Petersburg',866,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (31, 4,'Snowy Excalibur Resort Sochi',699,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (32, 4,'Ruby Dome Hotel Sochi',893,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (33, 4,'Ancient Cliff Resort Sochi',719,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (34, 4,'Olive Pinnacle Hotel & Spa Sochi',884,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (35, 4,'Sunrise Park Resort Sochi',973,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (36, 4,'Western Spire Resort & Spa Sochi',886,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (37, 4,'Fantasy Resort Sochi',762,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (38, 4,'Stellar Resort Sochi',973,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (39, 4,'Harborview Hotel Sochi',514,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (40, 4,'Nimbus Hotel Sochi',817,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (41, 5,'Snowy Excalibur Resort Kazan',687,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (42, 5,'Ruby Dome Hotel Kazan',628,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (43, 5,'Ancient Cliff Resort Kazan',568,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (44, 5,'Olive Pinnacle Hotel & Spa Kazan',881,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (45, 5,'Sunrise Park Resort Kazan',799,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (46, 5,'Western Spire Resort & Spa Kazan',844,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (47, 5,'Fantasy Resort Kazan',606,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (48, 5,'Stellar Resort Kazan',828,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (49, 5,'Harborview Hotel Kazan',944,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (50, 5,'Nimbus Hotel Kazan',905,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (51, 6,'Snowy Excalibur Resort Saransk',885,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (52, 6,'Ruby Dome Hotel Saransk',730,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (53, 6,'Ancient Cliff Resort Saransk',950,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (54, 6,'Olive Pinnacle Hotel & Spa Saransk',524,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (55, 6,'Sunrise Park Resort Saransk',695,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (56, 6,'Western Spire Resort & Spa Saransk',833,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (57, 6,'Fantasy Resort Saransk',997,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (58, 6,'Stellar Resort Saransk',581,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (59, 6,'Harborview Hotel Saransk',841,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (60, 6,'Nimbus Hotel Saransk',715,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (61, 7,'Snowy Excalibur Resort Kaliningrad',878,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (62, 7,'Ruby Dome Hotel Kaliningrad',815,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (63, 7,'Ancient Cliff Resort Kaliningrad',829,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (64, 7,'Olive Pinnacle Hotel & Spa Kaliningrad',505,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (65, 7,'Sunrise Park Resort Kaliningrad',629,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (66, 7,'Western Spire Resort & Spa Kaliningrad',956,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (67, 7,'Fantasy Resort Kaliningrad',805,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (68, 7,'Stellar Resort Kaliningrad',973,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (69, 7,'Harborview Hotel Kaliningrad',561,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (70, 7,'Nimbus Hotel Kaliningrad',632,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (71, 8,'Snowy Excalibur Resort Samara',612,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (72, 8,'Ruby Dome Hotel Samara',513,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (73, 8,'Ancient Cliff Resort Samara',870,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (74, 8,'Olive Pinnacle Hotel & Spa Samara',674,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (75, 8,'Sunrise Park Resort Samara',764,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (76, 8,'Western Spire Resort & Spa Samara',754,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (77, 8,'Fantasy Resort Samara',650,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (78, 8,'Stellar Resort Samara',960,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (79, 8,'Harborview Hotel Samara',778,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (80, 8,'Nimbus Hotel Samara',846,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (81, 9,'Snowy Excalibur Resort Rostov',761,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (82, 9,'Ruby Dome Hotel Rostov',537,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (83, 9,'Ancient Cliff Resort Rostov',871,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (84, 9,'Olive Pinnacle Hotel & Spa Rostov',639,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (85, 9,'Sunrise Park Resort Rostov',598,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (86, 9,'Western Spire Resort & Spa Rostov',946,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (87, 9,'Fantasy Resort Rostov',891,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (88, 9,'Stellar Resort Rostov',728,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (89, 9,'Harborview Hotel Rostov',901,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (90, 9,'Nimbus Hotel Rostov',942,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (91, 10,'Snowy Excalibur Resort Nizhny Novgorod',863,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (92, 10,'Ruby Dome Hotel Nizhny Novgorod',921,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (93, 10,'Ancient Cliff Resort Nizhny Novgorod',563,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (94, 10,'Olive Pinnacle Hotel & Spa Nizhny Novgorod',976,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (95, 10,'Sunrise Park Resort Nizhny Novgorod',680,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (96, 10,'Western Spire Resort & Spa Nizhny Novgorod',679,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (97, 10,'Fantasy Resort Nizhny Novgorod',896,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (98, 10,'Stellar Resort Nizhny Novgorod',690,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (99, 10,'Harborview Hotel Nizhny Novgorod',680,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (100, 10,'Nimbus Hotel Nizhny Novgorod',792,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (101, 11,'Snowy Excalibur Resort Volgograd',556,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (102, 11,'Ruby Dome Hotel Volgograd',814,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (103, 11,'Ancient Cliff Resort Volgograd',955,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (104, 11,'Olive Pinnacle Hotel & Spa Volgograd',564,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (105, 11,'Sunrise Park Resort Volgograd',851,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (106, 11,'Western Spire Resort & Spa Volgograd',571,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (107, 11,'Fantasy Resort Volgograd',703,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (108, 11,'Stellar Resort Volgograd',695,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (109, 11,'Harborview Hotel Volgograd',517,'Avenida Michel Temer, 666','Um hotel excelente.');
INSERT INTO hotel (id_hotel, id_cidade, nome, capacidade, endereco, descricao) VALUES (110, 11,'Nimbus Hotel Volgograd',593,'Avenida Michel Temer, 666','Um hotel excelente.');
