START TRANSACTION;
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('692','PASS','000858514','Clavelle','19770718','Iraq');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('693','PASS','000808436','Bertovich','19860213','Albania');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('694','PASS','000395553','Glidden','19780707','Brazil');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('695','PASS','000247619','Etters','19770118','Georgia');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('696','PASS','000278929','Albrekht','19701006','Argentina');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('697','PASS','000738704','Desutter','19830305','Zealand');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('698','PASS','000716530','Bandle','19721218','Hungary');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('699','PASS','000796800','Cogill','19770119','Chad');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('700','PASS','000293686','Eischens','19820811','Philippines');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('701','PASS','000688715','Beas','19890604','Nepal');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('702','PASS','000827741','Geml','19831101','Syria');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('703','PASS','000533736','Govindeisami','19720523','Algeria');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('704','PASS','000189366','Addiego','19811011','Vietnam');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('705','PASS','000281210','Cutillo','19810207','Syria');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('706','PASS','000577016','Alden','19800401','Serbia');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('707','PASS','000231617','Cockrum','19831227','Mozambique');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('708','PASS','000686740','Delage','19790116','Denmark');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('709','PASS','000123280','Grauel','19871116','Chad');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('710','PASS','000338670','Aveado','19730304','Egypt');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('711','PASS','000981625','Copeman','19730908','Rica');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('712','PASS','000441620','Gucwa','19740909','Denmark');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('713','PASS','000421830','Greening','19890502','Iran');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('714','PASS','000570995','Cashwell','19700704','Barbados');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('715','PASS','000736207','Denenberg','19760827','Spain');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('716','PASS','000377675','Donya','19880922','Mozambique');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('717','PASS','000900264','Brutus','19860224','Belgium');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('718','PASS','000279064','Cuadro','19800301','Switzerland');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('719','PASS','000262801','Delaportilla','19880108','Mozambique');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('720','PASS','000170538','Briddick','19700816','Luxembourg');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('721','PASS','000103875','Auxier','19790914','Cuba');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('722','PASS','000492203','Goodnoe','19820609','Denmark');
INSERT INTO pessoa (id_pessoa, tipo_documento,documento,nome,data_nascimento,nome_pais_origem) VALUES ('723','PASS','000398051','Borsos','19730111','Singapore');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('692','RUS','Fleisher');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('693','SAU','Fuse');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('694','EGY','Elinore');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('695','URY','Bandyk');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('696','POR','Coons');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('697','ESP','Devino');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('698','MAR','Bonadurer');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('699','IRN','Diak');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('700','FRA','Bockrath');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('701','AUS','Bartram');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('702','PER','Galardi');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('703','DEN','Gerloff');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('704','ARG','Agerter');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('705','ISL','Gavalis');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('706','CRO','Dicke');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('707','NIG','Gengler');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('708','BRA','Botti');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('709','SWI','Bobet');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('710','CRI','Faulkenberry');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('711','SRB','Carlton');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('712','GER','Delzer');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('713','MEX','Bankson');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('714','SWE','Etkin');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('715','KOR','Doane');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('716','BEL','Fukushima');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('717','PAN','Calvetti');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('718','TUN','Dagesse');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('719','ENG','Ahrenstorff');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('720','POL','Drobot');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('721','SEN','Dunmead');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('722','COL','Deja');
INSERT INTO tecnico (id_pessoa,codigo_pais_treina,nome_conhecido) VALUES ('723','JPN','Fils');
COMMIT;